AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  NameofTable: 
    Description: "Ingresa nombre de la tabla"
    Type: String

Resources:
  UsersDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref NameofTable
      KeySchema:
        - AttributeName: "id"
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: "apellido"
          AttributeType: String
        - AttributeName: "edad"
          AttributeType: Number
        - AttributeName: "nombre"
          AttributeType: String



